"""
coding_agent.py — Guidelines Validation Agent

Model: GPT-4o-mini
Role: Reviews the final formatted report to ensure it complies with
      the Phase 4 CLAUDE.md guidelines (e.g., no LLM hallucinations
      about rule classification, clear deterministic separation).
"""

from .llm_client import call_llm
import os


def validate_report(report_text: str) -> str:
    """Validate the final report against the project guidelines.
    
    Args:
        report_text: The markdown report generated by the formatting agent.
        
    Returns:
        A compliance status message.
    """
    # Read CLAUDE.md for rules
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    claude_md_path = os.path.join(project_root, "CLAUDE.md")
    
    try:
        with open(claude_md_path, "r", encoding="utf-8") as f:
            guidelines = f.read()
    except Exception:
        guidelines = "Guidelines file not found."
        
    # Truncate guidelines to the core rules section to conserve tokens.
    guidelines_excerpt = guidelines[:2000]

    prompt = f"""You are an automated compliance auditor (Layer 3 tooling).
Review the following Fleet Telemetry Report against our project guidelines.

--- CLAUDE.md GUIDELINES ---
{guidelines_excerpt}

--- REPORT TO VALIDATE ---
{report_text}

--- INSTRUCTIONS ---
Check specifically for:
1. "Rules decide -> LLM explains": Does the report present the health status as a hard fact rather than a guess?
2. Did the LLM invent sensors or data not present in standard telemetry?

Output a brief compliance verdict starting with either "COMPLIANT:" or "NON-COMPLIANT:".
Provide 1-2 sentences of justification.
"""

    return call_llm(
        prompt=prompt,
        provider="openai",
        model="gpt-4o-mini",
        system_prompt="You are a strict compliance checker. You verify that AI outputs follow project rules."
    )
